package com.wahlhalla.worldbuilder.geography;

public enum Climate {
    ALPINE_CLIMATE,
    DESERT_CLIMATE,
    ARID_CLIMATE,
    HUMID_CONTINENTAL_CLIMATE,
    HUMID_SUBTROPICAL_CLIMATE,
    ICE_CAP_CLIMATE,
    OCEANIC_CLIMATE,
    SUBARCTIC_CLIMATE,
    SEMI_ARID_CLIMATE,
    MEDITERRANEAN_CLIMATE,
    TROPICAL_MONSOON_CLIMATE,
    TROPICAL_RAINFOREST_CLIMATE,
    TROPICAL_SAVANNA_CLIMATE,
    TUNDRA_CLIMATE,
    POLAR_CLIMATE,
    OTHER;
}
